name: CI
on:
  push:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run:  pip install -r requirements.txt

    - name: Install Robot Framework
      run:  rfbrowser init

    - name: Run Robot Framework
      run:  robot -d reports Testsuites/test_pass.robot

    - name: Upload Test Results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: reports
        path: reports

    - name: Upload Test File
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test
        path: test

  report:
      if: always()
      needs: [test]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports

      - name: Robot Reporter
        uses: joonvena/robotframework-reporter-action@v2.3
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}    